version: '3'
services:

  #PHP Service
  app_quiz:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/passport
    container_name: app_quiz
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_quiz:
    image: nginx:alpine
    container_name: webserver_quiz
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_quiz:
    image: mysql:5.7.22
    container_name: db_quiz
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_ROOT_PASSWORD: senharoot
      MYSQL_USER: quiz
      MYSQL_PASSWORD: senha123
      SERVICE_TAGS: dev
      SERVICE_NAME: db_quiz
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
